# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Jul 12 15:52:25 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 637)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabla_tipo = QtGui.QTableView(self.centralwidget)
        self.tabla_tipo.setGeometry(QtCore.QRect(20, 20, 161, 291))
        self.tabla_tipo.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabla_tipo.setObjectName("tabla_tipo")
        self.tabla_animal = QtGui.QTableView(self.centralwidget)
        self.tabla_animal.setGeometry(QtCore.QRect(200, 20, 201, 291))
        self.tabla_animal.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabla_animal.setObjectName("tabla_animal")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 330, 381, 123))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_editar_tipo = QtGui.QPushButton(self.layoutWidget)
        self.btn_editar_tipo.setObjectName("btn_editar_tipo")
        self.horizontalLayout_2.addWidget(self.btn_editar_tipo)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_editar_animal = QtGui.QPushButton(self.layoutWidget)
        self.btn_editar_animal.setObjectName("btn_editar_animal")
        self.verticalLayout_3.addWidget(self.btn_editar_animal)
        self.eliminar_animal = QtGui.QPushButton(self.layoutWidget)
        self.eliminar_animal.setObjectName("eliminar_animal")
        self.verticalLayout_3.addWidget(self.eliminar_animal)
        self.btn_agregar_animal = QtGui.QPushButton(self.layoutWidget)
        self.btn_agregar_animal.setObjectName("btn_agregar_animal")
        self.verticalLayout_3.addWidget(self.btn_agregar_animal)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 515, 143, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 550, 131, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(11, 584, 43, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(11, 481, 212, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(230, 480, 671, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_cant_ani = QtGui.QLabel(self.layoutWidget1)
        self.lbl_cant_ani.setText("")
        self.lbl_cant_ani.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_cant_ani.setObjectName("lbl_cant_ani")
        self.verticalLayout.addWidget(self.lbl_cant_ani)
        self.label_descripcion_tipo = QtGui.QLabel(self.layoutWidget1)
        self.label_descripcion_tipo.setLineWidth(1)
        self.label_descripcion_tipo.setText("")
        self.label_descripcion_tipo.setTextFormat(QtCore.Qt.PlainText)
        self.label_descripcion_tipo.setScaledContents(False)
        self.label_descripcion_tipo.setObjectName("label_descripcion_tipo")
        self.verticalLayout.addWidget(self.label_descripcion_tipo)
        self.label_nombre_cientifico = QtGui.QLabel(self.layoutWidget1)
        self.label_nombre_cientifico.setText("")
        self.label_nombre_cientifico.setTextFormat(QtCore.Qt.PlainText)
        self.label_nombre_cientifico.setObjectName("label_nombre_cientifico")
        self.verticalLayout.addWidget(self.label_nombre_cientifico)
        self.label_datos = QtGui.QLabel(self.layoutWidget1)
        self.label_datos.setText("")
        self.label_datos.setTextFormat(QtCore.Qt.PlainText)
        self.label_datos.setWordWrap(True)
        self.label_datos.setMargin(0)
        self.label_datos.setObjectName("label_datos")
        self.verticalLayout.addWidget(self.label_datos)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(410, 10, 671, 431))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 669, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Animales", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_editar_tipo.setText(QtGui.QApplication.translate("MainWindow", "Editar Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_editar_animal.setText(QtGui.QApplication.translate("MainWindow", "Editar Animal", None, QtGui.QApplication.UnicodeUTF8))
        self.eliminar_animal.setText(QtGui.QApplication.translate("MainWindow", "Eliminar Animal", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_agregar_animal.setText(QtGui.QApplication.translate("MainWindow", "Agregar Animal", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Descripcion del tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Nombre Científico", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Cantidad de animales del tipo", None, QtGui.QApplication.UnicodeUTF8))

